name: Ensure generated files are up-to-date

on:
  workflow_call:
    secrets:
      app_id:
        description: 'GitHub App ID for pushing commits that trigger workflows'
        required: true
      app_secret:
        description: 'GitHub PAT for pushing commits that trigger workflows'
        required: true

permissions:
  contents: write

jobs:
  run-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse .tool-versions
        uses: wistia/parse-tool-versions@v2.1.1

      - name: Setup Go
        uses: ./.github/actions/go-setup-cache

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.TERRAFORM }}"

      - name: Run integrity check
        run: make tidy

      - name: Fix tracers
        run: ./scripts/fix-tracers.sh

      - name: Generate all code
        run: make --jobs=4 generate

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version: "v${{ env.GOLANGCI_LINT }}"

      - name: Format code
        run: make fmt

      - name: Commit generated changes if any
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "‚úÖ No changes detected."
            exit 0
          fi

          echo "üìù Generated files are not up to date. Committing changes..."
          git status --short

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "chore: auto-commit generated changes"
          git push origin HEAD:${{ github.head_ref }}

          echo "‚úÖ Changes committed and pushed successfully."

          # There were changes, exit with an error code so that the workflow fails.
          exit 1
