name: Pull Request

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  cache-deps:
    uses: ./.github/workflows/init-cache.yml
  integrity-check:
    uses: ./.github/workflows/pr-go-integrity.yml
    needs: [ cache-deps ]
  lint:
    uses: ./.github/workflows/lint.yml
    needs: [ cache-deps ]
  out-of-order-migrations:
    uses: ./.github/workflows/out-of-order-migrations.yml
  unit-tests:
    needs: [ cache-deps ]
    uses: ./.github/workflows/pr-tests.yml
  integration-tests:
    needs: [ lint, unit-tests, out-of-order-migrations ]
    uses: ./.github/workflows/integration_tests.yml
  publish-test-results:
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          # Docker build artifacts have to ignored
          # https://github.com/actions/toolkit/pull/1874
          pattern: "!*.dockerbuild"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          fail_on: 'errors'
          files: "artifacts/**/*.xml"
